# Generated by Django 5.1.5 on 2025-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiny_url", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tinyurl",
            index=models.Index(
                fields=["short_url"], name="tiny_url_ti_short_u_e67a48_idx"
            ),
        ),
    ]
