# Generated by Django 5.1.5 on 2025-02-20 06:15

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="image",
            field=models.ImageField(
                storage=gdstorage.storage.GoogleDriveStorage(), upload_to="screenshots"
            ),
        ),
    ]
